//package com.example.navigation
//
//import android.annotation.SuppressLint
//import androidx.compose.foundation.layout.width
//import androidx.compose.foundation.lazy.LazyColumn
//import androidx.compose.material3.DrawerValue
//import androidx.compose.material3.Icon
//import androidx.compose.material3.ModalDrawerSheet
//import androidx.compose.material3.ModalNavigationDrawer
//import androidx.compose.material3.NavigationDrawerItem
//import androidx.compose.material3.NavigationDrawerItemDefaults
//import androidx.compose.material3.rememberDrawerState
//import androidx.compose.runtime.Composable
//import androidx.compose.runtime.getValue
//import androidx.compose.runtime.rememberCoroutineScope
//import androidx.compose.ui.Modifier
//import androidx.compose.ui.res.stringResource
//import androidx.compose.ui.unit.dp
//import androidx.navigation.NavDestination.Companion.hierarchy
//import androidx.navigation.NavHostController
//import androidx.navigation.compose.currentBackStackEntryAsState
//import com.ortega.design.auth.HeaderImageComponent
//import com.ortega.design.common.TextComponent
//import com.ortega.design.theme.Black
//import com.ortega.design.theme.DarkGray
//import com.ortega.design.theme.White
//import com.ortega.home.R
//import kotlinx.coroutines.delay
//import kotlinx.coroutines.launch
//
